services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "--silent"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: colorfit
      MYSQL_USER: colorfit
      MYSQL_PASSWORD: colorfit
    ports:
      - 3306:3306
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db-data:
